// Generated by https://quicktype.io

export interface TestTs {
    formResponseId: number;
    patientId: number;
    actionPlanGiven: boolean;
    managedByExternalProvider: boolean;
    dateOfLastCommunicationByExternalProvider: string;
    followupPhoneCallOneToTwoWeeks: boolean;
    dateOfFollowupCall: string;
    oneMonthFollowupVisit: boolean;
    dateOfOneMonthVisit: string;
    oneMonthFolllowupPHQ9Score: number;
}
