// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace org.cchmc.pho.identity.EntityModels
{
    public partial class Login
    {
        public int Id { get; set; }
        public int? UserTypeId { get; set; }
        public int StaffId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool? PendingFlag { get; set; }
        public bool? DeletedFlag { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOnDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string DeletedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public int? AccessFailedCount { get; set; }
        public bool? LockoutFlag { get; set; }
        public DateTime? LegalDisclaimerSigned { get; set; }
        public string RefreshToken { get; set; }
    }
}