// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace org.cchmc.pho.identity.EntityModels
{
    public partial class Staff
    {
        public int Id { get; set; }
        public int StaffTypeId { get; set; }
        public int? StaffPositionId { get; set; }
        public int? CredentialId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
        public int? Npi { get; set; }
        public string CchmcProvId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool? ActiveFlag { get; set; }
        public bool? DeletedFlag { get; set; }
        public int? CreatedById { get; set; }
        public DateTime? CreatedOnDate { get; set; }
        public int? ModifiedById { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? DeletedById { get; set; }
        public DateTime? DeletedDate { get; set; }
    }
}